# Generated by Django 4.0.4 on 2022-05-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_documento_proprietario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
