# Generated by Django 4.0.4 on 2022-05-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documento_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='proprietario_documento',
            new_name='pertence',
        ),
    ]
